"""initial schema

Revision ID: 2b6f55486b4d
Revises: 
Create Date: 2026-02-27 17:35:51.299581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b6f55486b4d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ev_battery_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('hv_battery_soc', sa.Numeric(), nullable=True),
    sa.Column('hv_battery_actual_soc', sa.Numeric(), nullable=True),
    sa.Column('hv_battery_voltage', sa.Numeric(), nullable=True),
    sa.Column('hv_battery_amperage', sa.Numeric(), nullable=True),
    sa.Column('hv_battery_kw', sa.Numeric(), nullable=True),
    sa.Column('hv_battery_capacity', sa.Numeric(), nullable=True),
    sa.Column('hv_battery_range', sa.Numeric(), nullable=True),
    sa.Column('hv_battery_max_range', sa.Numeric(), nullable=True),
    sa.Column('hv_battery_temperature', sa.Numeric(), nullable=True),
    sa.Column('lv_battery_level', sa.Numeric(), nullable=True),
    sa.Column('lv_battery_voltage', sa.Numeric(), nullable=True),
    sa.Column('motor_voltage', sa.Numeric(), nullable=True),
    sa.Column('motor_amperage', sa.Numeric(), nullable=True),
    sa.Column('motor_kw', sa.Numeric(), nullable=True),
    sa.Column('performance_status', sa.String(), nullable=True),
    sa.Column('source_system', sa.String(length=100), nullable=True),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('original_timestamp', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ev_battery_status_device_id', 'ev_battery_status', ['device_id'], unique=False)
    op.create_index('idx_ev_battery_status_recorded_at', 'ev_battery_status', ['recorded_at'], unique=False)
    op.create_index('idx_ev_battery_status_source_system', 'ev_battery_status', ['source_system'], unique=False)
    op.create_table('ev_charging_networks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('network_name', sa.String(), nullable=False),
    sa.Column('cost_per_kwh', sa.Numeric(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ev_charging_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('charge_type', sa.String(), nullable=True),
    sa.Column('location_name', sa.String(), nullable=True),
    sa.Column('plug_status', sa.String(), nullable=True),
    sa.Column('charging_status', sa.String(), nullable=True),
    sa.Column('station_status', sa.String(), nullable=True),
    sa.Column('charging_voltage', sa.Numeric(), nullable=True),
    sa.Column('charging_amperage', sa.Numeric(), nullable=True),
    sa.Column('charging_kw', sa.Numeric(), nullable=True),
    sa.Column('session_start_utc', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('session_end_utc', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('estimated_end_utc', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('charge_duration_seconds', sa.Numeric(), nullable=True),
    sa.Column('plugged_in_duration_seconds', sa.Numeric(), nullable=True),
    sa.Column('start_soc', sa.Numeric(), nullable=True),
    sa.Column('end_soc', sa.Numeric(), nullable=True),
    sa.Column('energy_kwh', sa.Numeric(), nullable=True),
    sa.Column('cost', sa.Numeric(), nullable=True),
    sa.Column('cost_without_overrides', sa.Numeric(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('max_power', sa.Numeric(), nullable=True),
    sa.Column('min_power', sa.Numeric(), nullable=True),
    sa.Column('miles_added', sa.Numeric(), nullable=True),
    sa.Column('source_system', sa.String(length=100), nullable=True),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('original_timestamp', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ev_charging_session_device_id', 'ev_charging_session', ['device_id'], unique=False)
    op.create_index('idx_ev_charging_session_is_complete', 'ev_charging_session', ['is_complete'], unique=False, postgresql_where=sa.text('is_complete = true'))
    op.create_index('idx_ev_charging_session_session_start_utc', 'ev_charging_session', ['session_start_utc'], unique=False)
    op.create_index('idx_ev_charging_session_source_system', 'ev_charging_session', ['source_system'], unique=False)
    op.create_table('ev_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('latitude', sa.Numeric(), nullable=True),
    sa.Column('longitude', sa.Numeric(), nullable=True),
    sa.Column('gps_accuracy', sa.Numeric(), nullable=True),
    sa.Column('altitude', sa.Numeric(), nullable=True),
    sa.Column('compass_direction', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('location_type', sa.String(), nullable=True),
    sa.Column('source_system', sa.String(length=100), nullable=True),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('original_timestamp', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ev_location_device_id', 'ev_location', ['device_id'], unique=False)
    op.create_index('idx_ev_location_device_recorded_at', 'ev_location', ['device_id', 'recorded_at'], unique=False)
    op.create_index('idx_ev_location_recorded_at', 'ev_location', ['recorded_at'], unique=False)
    op.create_index('idx_ev_location_source_system', 'ev_location', ['source_system'], unique=False)
    op.create_table('ev_location_lookup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_name', sa.String(), nullable=False),
    sa.Column('latitude', sa.Numeric(), nullable=True),
    sa.Column('longitude', sa.Numeric(), nullable=True),
    sa.Column('location_type', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ev_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('computed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.Column('total_sessions', sa.Integer(), nullable=True),
    sa.Column('total_energy_kwh', sa.Numeric(), nullable=True),
    sa.Column('total_cost', sa.Numeric(), nullable=True),
    sa.Column('total_miles_added', sa.Numeric(), nullable=True),
    sa.Column('avg_session_duration_seconds', sa.Numeric(), nullable=True),
    sa.Column('avg_energy_per_session_kwh', sa.Numeric(), nullable=True),
    sa.Column('avg_cost_per_kwh', sa.Numeric(), nullable=True),
    sa.Column('avg_miles_per_kwh', sa.Numeric(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ev_trip_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('end_time', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('distance', sa.Numeric(), nullable=True),
    sa.Column('duration', sa.Numeric(), nullable=True),
    sa.Column('energy_consumed', sa.Numeric(), nullable=True),
    sa.Column('efficiency', sa.Numeric(), nullable=True),
    sa.Column('range_regenerated', sa.Numeric(), nullable=True),
    sa.Column('ambient_temp', sa.Numeric(), nullable=True),
    sa.Column('cabin_temp', sa.Numeric(), nullable=True),
    sa.Column('outside_air_temp', sa.Numeric(), nullable=True),
    sa.Column('driving_score', sa.Numeric(), nullable=True),
    sa.Column('speed_score', sa.Numeric(), nullable=True),
    sa.Column('acceleration_score', sa.Numeric(), nullable=True),
    sa.Column('deceleration_score', sa.Numeric(), nullable=True),
    sa.Column('start_location_id', sa.Integer(), nullable=True),
    sa.Column('end_location_id', sa.Integer(), nullable=True),
    sa.Column('electrical_efficiency', sa.Numeric(), nullable=True),
    sa.Column('brake_torque', sa.Numeric(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('source_system', sa.String(length=100), nullable=True),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('original_timestamp', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ev_trip_metrics_device_id', 'ev_trip_metrics', ['device_id'], unique=False)
    op.create_index('idx_ev_trip_metrics_source_system', 'ev_trip_metrics', ['source_system'], unique=False)
    op.create_index('idx_ev_trip_metrics_start_time', 'ev_trip_metrics', ['start_time'], unique=False)
    op.create_table('ev_vehicle_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('odometer', sa.Numeric(), nullable=True),
    sa.Column('speed', sa.Numeric(), nullable=True),
    sa.Column('accelerator_position', sa.Numeric(), nullable=True),
    sa.Column('brake_status', sa.String(), nullable=True),
    sa.Column('gear_position', sa.String(), nullable=True),
    sa.Column('parking_brake', sa.String(), nullable=True),
    sa.Column('ignition_status', sa.String(), nullable=True),
    sa.Column('remote_start_status', sa.String(), nullable=True),
    sa.Column('coolant_temp', sa.Numeric(), nullable=True),
    sa.Column('torque_at_transmission', sa.Numeric(), nullable=True),
    sa.Column('door_lock_status', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tire_pressure', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('indicators', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('brake_torque', sa.Numeric(), nullable=True),
    sa.Column('wheel_torque_status', sa.String(), nullable=True),
    sa.Column('yaw_rate', sa.Numeric(), nullable=True),
    sa.Column('acceleration', sa.Numeric(), nullable=True),
    sa.Column('engine_speed', sa.Numeric(), nullable=True),
    sa.Column('outside_temperature', sa.Numeric(), nullable=True),
    sa.Column('cabin_temperature', sa.Numeric(), nullable=True),
    sa.Column('deep_sleep_status', sa.String(), nullable=True),
    sa.Column('device_connectivity', sa.String(), nullable=True),
    sa.Column('evcc_status', sa.String(), nullable=True),
    sa.Column('seatbelt_status', sa.String(), nullable=True),
    sa.Column('remote_start_countdown', sa.Numeric(), nullable=True),
    sa.Column('source_system', sa.String(length=100), nullable=True),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('original_timestamp', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ev_vehicle_status_device_id', 'ev_vehicle_status', ['device_id'], unique=False)
    op.create_index('idx_ev_vehicle_status_recorded_at', 'ev_vehicle_status', ['recorded_at'], unique=False)
    op.create_index('idx_ev_vehicle_status_source_system', 'ev_vehicle_status', ['source_system'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ev_vehicle_status_source_system', table_name='ev_vehicle_status')
    op.drop_index('idx_ev_vehicle_status_recorded_at', table_name='ev_vehicle_status')
    op.drop_index('idx_ev_vehicle_status_device_id', table_name='ev_vehicle_status')
    op.drop_table('ev_vehicle_status')
    op.drop_index('idx_ev_trip_metrics_start_time', table_name='ev_trip_metrics')
    op.drop_index('idx_ev_trip_metrics_source_system', table_name='ev_trip_metrics')
    op.drop_index('idx_ev_trip_metrics_device_id', table_name='ev_trip_metrics')
    op.drop_table('ev_trip_metrics')
    op.drop_table('ev_statistics')
    op.drop_table('ev_location_lookup')
    op.drop_index('idx_ev_location_source_system', table_name='ev_location')
    op.drop_index('idx_ev_location_recorded_at', table_name='ev_location')
    op.drop_index('idx_ev_location_device_recorded_at', table_name='ev_location')
    op.drop_index('idx_ev_location_device_id', table_name='ev_location')
    op.drop_table('ev_location')
    op.drop_index('idx_ev_charging_session_source_system', table_name='ev_charging_session')
    op.drop_index('idx_ev_charging_session_session_start_utc', table_name='ev_charging_session')
    op.drop_index('idx_ev_charging_session_is_complete', table_name='ev_charging_session', postgresql_where=sa.text('is_complete = true'))
    op.drop_index('idx_ev_charging_session_device_id', table_name='ev_charging_session')
    op.drop_table('ev_charging_session')
    op.drop_table('ev_charging_networks')
    op.drop_index('idx_ev_battery_status_source_system', table_name='ev_battery_status')
    op.drop_index('idx_ev_battery_status_recorded_at', table_name='ev_battery_status')
    op.drop_index('idx_ev_battery_status_device_id', table_name='ev_battery_status')
    op.drop_table('ev_battery_status')
    # ### end Alembic commands ###
