"""add network_id to ev_location_lookup

Revision ID: 5f531bc75936
Revises: a1b2c3d4e5f6
Create Date: 2026-03-01 21:51:47.925840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f531bc75936'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ev_location_lookup', sa.Column('network_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ev_location_lookup', 'ev_charging_networks', ['network_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ev_location_lookup', type_='foreignkey')
    op.drop_column('ev_location_lookup', 'network_id')
    # ### end Alembic commands ###
