"""add_location_type_is_free_session_id_unique

Revision ID: 7086caea2990
Revises: 2b6f55486b4d
Create Date: 2026-02-27 22:01:48.392329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7086caea2990'
down_revision: Union[str, Sequence[str], None] = '2b6f55486b4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ev_charging_session', sa.Column('location_type', sa.String(length=20), nullable=True))
    op.add_column('ev_charging_session', sa.Column('is_free', sa.Boolean(), nullable=True))
    op.create_unique_constraint('uq_ev_charging_session_session_id', 'ev_charging_session', ['session_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_ev_charging_session_session_id', 'ev_charging_session', type_='unique')
    op.drop_column('ev_charging_session', 'is_free')
    op.drop_column('ev_charging_session', 'location_type')
    # ### end Alembic commands ###
