{
 "title": "LightningROD",
 "description": "Lightning Record of Docks (logs) for your F-150 Lightning!",
 "time": { "from": "2023-08-10T17:08:11.000Z", "to": "2023-09-20T19:38:18.000Z" },
 "panels": [
  {
   "title": "Last Charge",
   "type": "stat",
   "fieldConfig": { "defaults": { "unit": "dateTimeAsUSNoDateIfToday" } },
   "targets": [
    {
     "rawSql": "SELECT time_stamp FROM energytransferlogs LIMIT 50 "
    }
   ]
  },
  {
   "title": "Average Time Between Charges",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "targets": [
    {
     "rawSql": "WITH charging_intervals AS (\r\n  SELECT\r\n    plug_out_time AS previous_time,\r\n    LEAD(plug_in_time) OVER (ORDER BY plug_out_time) AS next_time\r\n  FROM\r\n    energytransferlogs\r\n)\r\nSELECT\r\n  ROUND(EXTRACT(EPOCH FROM AVG(next_time - previous_time))) AS avg_time_between_charges\r\nFROM\r\n  charging_intervals\r\nWHERE\r\n  next_time IS NOT NULL\r\n  AND previous_time IS NOT NULL;\r\n"
    }
   ]
  },
  {
   "title": "Average Charge Session",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT soc_difference FROM energytransferlogs LIMIT 50 "
    },
    {
     "rawSql": "SELECT total_distance_added FROM energytransferlogs LIMIT 50 "
    },
    {
     "rawSql": "SELECT total_time FROM energytransferlogs LIMIT 50 "
    }
   ]
  },
  {
   "title": "AC/DC - Duration",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  charger_type,\r\n  SUM(CASE WHEN charger_type IN ('AC_BASIC') THEN total_plugged_in_time ELSE 0 END) AS total_duration_minutes\r\nFROM energyTransferLogs\r\nWHERE charger_type IN ('AC_BASIC')\r\nGROUP BY charger_type;\r\n"
    },
    {
     "rawSql": "SELECT\r\n  charger_type,\r\n  SUM(CASE WHEN charger_type IN ('DC_FAST') THEN total_plugged_in_time ELSE 0 END) AS total_duration_minutes\r\nFROM energyTransferLogs\r\nWHERE charger_type IN ('DC_FAST')\r\nGROUP BY charger_type;\r\n"
    }
   ]
  },
  {
   "title": "Logged Charges",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM energytransferlogs LIMIT 50 "
    }
   ]
  },
  {
   "title": "Total Cost",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(cost) FROM energytransferlogs LIMIT 50 "
    }
   ]
  },
  {
   "title": "Total Energy Consumed",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT energy_consumed FROM energytransferlogs LIMIT 50 "
    }
   ]
  },
  {
   "title": "Total Charging Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(total_time) FROM energytransferlogs LIMIT 50 "
    }
   ]
  },
  {
   "title": "Charging Graph",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "WITH charging_discharging AS (\r\n  SELECT\r\n    plug_out_time AS time,\r\n    soc_last AS value,\r\n    'Charging' AS status\r\n  FROM\r\n    energyTransferLogs\r\n  WHERE\r\n    plug_out_time IS NOT NULL\r\n\r\n  UNION ALL\r\n\r\n  SELECT\r\n    plug_in_time AS time,\r\n    soc_first AS value,\r\n    'Discharging' AS status\r\n  FROM\r\n    energyTransferLogs\r\n  WHERE\r\n    plug_in_time IS NOT NULL\r\n)\r\nSELECT\r\n  time,\r\n  value,\r\n  status\r\nFROM\r\n  charging_discharging\r\nORDER BY\r\n  time DESC;\r\n"
    }
   ]
  },
  {
   "title": "AC Charging",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "rawSql": "SELECT time_stamp, power_min, power_max, power_average FROM energytransferlogs WHERE charger_type = 'AC_BASIC' LIMIT 50 "
    }
   ]
  },
  {
   "title": "AC/DC - kWh",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  charger_type,\r\n  SUM(CASE WHEN charger_type IN ('AC_BASIC') THEN energy_consumed ELSE 0 END) AS total_kWh\r\nFROM energyTransferLogs\r\nWHERE charger_type IN ('AC_BASIC')\r\nGROUP BY charger_type;\r\n"
    },
    {
     "rawSql": "SELECT\r\n  charger_type,\r\n  SUM(CASE WHEN charger_type IN ('DC_FAST') THEN energy_consumed ELSE 0 END) AS total_kWh\r\nFROM energyTransferLogs\r\nWHERE charger_type IN ('DC_FAST')\r\nGROUP BY charger_type;\r\n"
    }
   ]
  },
  {
   "title": "Charging Locations",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    CASE\r\n        WHEN location_name = 'Work' THEN 'Work'\r\n        WHEN location_name = 'Home' THEN 'Home'\r\n        ELSE 'Other'\r\n    END AS location_group,\r\n    COUNT(*) AS count\r\nFROM\r\n    energyTransferLogs\r\nGROUP BY\r\n    location_group\r\n"
    }
   ]
  },
  {
   "title": "DC Charging",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "rawSql": "SELECT time_stamp, power_min, power_max, power_average FROM energytransferlogs WHERE charger_type = 'DC_FAST' LIMIT 50 "
    }
   ]
  }
 ]
}